# SPDX-License-Identifier: GPL-2.0-only
cdns_mhdp_drmcore-y := cdns-mhdp-common.o cdns-mhdp-audio.o cdns-mhdp-dp.o
cdns_mhdp_drmcore-$(CONFIG_DRM_CDNS_DP) += cdns-dp-core.o
obj-$(CONFIG_DRM_CDNS_MHDP)		+= cdns_mhdp_drmcore.o
