/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Driver for TI TPS6598x USB Power Delivery controller family
 *
 * Copyright (C) 2017, Intel Corporation
 * Author: Heikki Krogerus <heikki.krogerus@linux.intel.com>
 */

#ifndef __TPS6598X_H__
#define __TPS6598X_H__


/* TPS_REG_INT_* bits */
#define TPS_REG_INT_USER_VID_ALT_MODE_OTHER_VDM		BIT(27+32)
#define TPS_REG_INT_USER_VID_ALT_MODE_ATTN_VDM		BIT(26+32)
#define TPS_REG_INT_USER_VID_ALT_MODE_EXIT		BIT(25+32)
#define TPS_REG_INT_USER_VID_ALT_MODE_ENTERED		BIT(24+32)
#define TPS_REG_INT_EXIT_MODES_COMPLETE			BIT(20+32)
#define TPS_REG_INT_DISCOVER_MODES_COMPLETE		BIT(19+32)
#define TPS_REG_INT_VDM_MSG_SENT			BIT(18+32)
#define TPS_REG_INT_VDM_ENTERED_MODE			BIT(17+32)
#define TPS_REG_INT_ERROR_UNABLE_TO_SOURCE		BIT(14+32)
#define TPS_REG_INT_SRC_TRANSITION			BIT(10+32)
#define TPS_REG_INT_ERROR_DISCHARGE_FAILED		BIT(9+32)
#define TPS_REG_INT_ERROR_MESSAGE_DATA			BIT(7+32)
#define TPS_REG_INT_ERROR_PROTOCOL_ERROR		BIT(6+32)
#define TPS_REG_INT_ERROR_MISSING_GET_CAP_MESSAGE	BIT(4+32)
#define TPS_REG_INT_ERROR_POWER_EVENT_OCCURRED		BIT(3+32)
#define TPS_REG_INT_ERROR_CAN_PROVIDE_PWR_LATER		BIT(2+32)
#define TPS_REG_INT_ERROR_CANNOT_PROVIDE_PWR		BIT(1+32)
#define TPS_REG_INT_ERROR_DEVICE_INCOMPATIBLE		BIT(0+32)
#define TPS_REG_INT_CMD2_COMPLETE			BIT(31)
#define TPS_REG_INT_CMD1_COMPLETE			BIT(30)
#define TPS_REG_INT_ADC_HIGH_THRESHOLD			BIT(29)
#define TPS_REG_INT_ADC_LOW_THRESHOLD			BIT(28)
#define TPS_REG_INT_PD_STATUS_UPDATE			BIT(27)
#define TPS_REG_INT_STATUS_UPDATE			BIT(26)
#define TPS_REG_INT_DATA_STATUS_UPDATE			BIT(25)
#define TPS_REG_INT_POWER_STATUS_UPDATE			BIT(24)
#define TPS_REG_INT_PP_SWITCH_CHANGED			BIT(23)
#define TPS_REG_INT_HIGH_VOLTAGE_WARNING		BIT(22)
#define TPS_REG_INT_USB_HOST_PRESENT_NO_LONGER		BIT(21)
#define TPS_REG_INT_USB_HOST_PRESENT			BIT(20)
#define TPS_REG_INT_GOTO_MIN_RECEIVED			BIT(19)
#define TPS_REG_INT_PR_SWAP_REQUESTED			BIT(17)
#define TPS_REG_INT_SINK_CAP_MESSAGE_READY		BIT(15)
#define TPS_REG_INT_SOURCE_CAP_MESSAGE_READY		BIT(14)
#define TPS_REG_INT_NEW_CONTRACT_AS_PROVIDER		BIT(13)
#define TPS_REG_INT_NEW_CONTRACT_AS_CONSUMER		BIT(12)
#define TPS_REG_INT_VDM_RECEIVED			BIT(11)
#define TPS_REG_INT_ATTENTION_RECEIVED			BIT(10)
#define TPS_REG_INT_OVERCURRENT				BIT(9)
#define TPS_REG_INT_BIST				BIT(8)
#define TPS_REG_INT_RDO_RECEIVED_FROM_SINK		BIT(7)
#define TPS_REG_INT_DR_SWAP_COMPLETE			BIT(5)
#define TPS_REG_INT_PR_SWAP_COMPLETE			BIT(4)
#define TPS_REG_INT_PLUG_EVENT				BIT(3)
#define TPS_REG_INT_HARD_RESET				BIT(1)
#define TPS_REG_INT_PD_SOFT_RESET			BIT(0)

#endif /* __TPS6598X_H__ */
